# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '7fe86338c8a57511291f6a5272f57162'
  config.secret_key = '73bb02296a7ed161e719b05d0d0d26ce'
  config.default_from = 'no-reply@monsite.fr'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
